### ISSUE TITLE
Please open your maven repository or

### ISSUE THREAD

**Issue by torsten-liermann** [evgeny-goldin/teamcity-plugins#1]
Please open your maven repository or remove your work from teamcity help/ plugin pages.

Thanks!

**Comment by evgeny-goldin** [comment]
Hi Torsten,

Yes, unfortunately I'm unable to keep my Artifactory Online instance open for anonymous access. If you mail me to evgenyg@gmail.com I can provide you with credentials for read-only access account.
Apologize for the inconvenience.
